steps:
  # --- Step 1: Clone the Git Repository ---
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/google/perfetto.git', '--branch', 'dev/zezeozue/perfette', '--single-branch', '.']

  # --- Step 2: Build the Container Image with Caching ---
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--tag=us-central1-docker.pkg.dev/brush-corprun-dev/perfetto/ui:latest'
      # Pull the latest image to use as a cache source
      - '--cache-from=us-central1-docker.pkg.dev/brush-corprun-dev/perfetto/ui:latest'
      - '.'
    # Allow this step to fail if the cache image doesn't exist (e.g., first build)
    allowFailure: true

  # --- Step 3: Push the potentially cached image to Artifact Registry ---
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/brush-corprun-dev/perfetto/ui:latest']

  # --- Step 4: Deploy the new image to Cloud Run ---
  # This step uses the gcloud CLI tool available in Cloud Build.
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'default' # Your service name is 'default'
      - '--project=brush-corprun-dev'
      - '--region=us-central1'
      - '--image=us-central1-docker.pkg.dev/brush-corprun-dev/perfetto/ui:latest'
      - '--port=80' # Explicitly specify the container port
      # --- Networking ---
      - '--ingress=internal-and-cloud-load-balancing'
      - '--network=cr-infra-vpc-network'
      - '--subnet=cr-infra-subnetwork'
      - '--vpc-egress=all-traffic'
      # --- Permissions ---
      - '--allow-unauthenticated'
      # IMPORTANT: Ensure this service account has Secret Accessor & Cloud Run Admin roles.
      # The runtime service account is now set by the setup_cloud_build.py script
      # on the service itself. Removing this flag ensures the deploy step runs
      # as the Cloud Build SA, which has the correct 'run.admin' permissions.
      - '--platform=managed'

# This tells Cloud Build the final image URL.
images:
- 'us-central1-docker.pkg.dev/brush-corprun-dev/perfetto/ui:latest'

# --- Improve Build Performance ---
# Use a more powerful machine type for faster compilation.
options:
  machineType: 'E2_HIGHCPU_8'